Use wine for testing.

diff --git a/.github/ytt/cc-container-alpine-cross-mingw64-gcc.yml b/.github/ytt/cc-container-alpine-cross-mingw64-gcc.yml
--- a/.github/ytt/cc-container-alpine-cross-mingw64-gcc.yml
+++ b/.github/ytt/cc-container-alpine-cross-mingw64-gcc.yml
@@ -7,9 +7,11 @@ name: 'CC - container Alpine mingw64-gcc'
   schedule: [cron: '15 1 * * 2'] # run weekly Tuesday 01:15 UTC
   workflow_dispatch: null
 env:
-  CMAKE_REQUIRED_QUIET: "OFF"
-  CTEST_OUTPUT_ON_FAILURE: "ON"
+  CMAKE_REQUIRED_QUIET: 'OFF'
+  CMAKE_VERBOSE_MAKEFILE: 'ON'
+  CTEST_OUTPUT_ON_FAILURE: 'ON'
   DEBIAN_FRONTEND: noninteractive
+  UPX_CONFIG_EXPECT_THREADS: 'ON'
   VERBOSE: 1
 
   # these are exactly like the GITHUB_xxx default environment variables
@@ -43,6 +45,8 @@ jobs:
       CC: 'x86_64-w64-mingw32-gcc -static'
       CXX: 'x86_64-w64-mingw32-g++ -static'
       CMAKE_AR: '/usr/bin/x86_64-w64-mingw32-ar' # CMAKE_AR is only needed on Alpine 3.11 and 3.12
+      CMAKE_SYSTEM_NAME: Windows
+      CMAKE_CROSSCOMPILING_EMULATOR: wine64
 
     steps:
 
@@ -74,3 +78,10 @@ jobs:
         run: 'make build/debug'
       - name: ${{ format('Build Release with {0} and {1}', env.CC, env.CXX) }}
         run: 'make build/release'
+
+      - run: 'apk add wine && mkdir -p ~/.wine && wineboot --init'
+      - name: 'Run ctest tests Debug'
+        run: 'cd build/debug && ctest'
+      - name: 'Run ctest tests Release'
+        if: success() || failure() # run this step even if the previous step failed
+        run: 'cd build/release && ctest'
